trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm test -- --reporter mocha-junit-reporter --reporter-options mochaFile=results/test-results.xml
  displayName: 'Run tests and generate XML report'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'results/test-results.xml'
    testRunTitle: 'JavaScript Tests'
  displayName: 'Publish test results'

- script: |
    npm run build
  displayName: 'Build the project'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'